//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.11 at 11:40:49 PM COT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://my-host/service-soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.systemia.consumersoap.contracts;
